language: rust

git:
  depth: 1

os:
  - windows

rust:
  - stable

matrix:
  fast_finish: true

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: txNDvv4iR5p97lhBDPKz+FsmsEAtTvh7sZboHk5aVRUn3VDsoJI0HwSNVJ81Jux2ncQnAYUe6DaiB6MhHxdxb3l7a2lsa7lrxiZ5ov4j39g21Iwsh4frQ4jFaxfo0LTmkSs6DMeliKkI/kKIy4l9yO/dD/4kzZbm7FwT6n1+KqYFELE6C9L/j+LARrUObfTGg+IhRaWqDs9WDWfc49cIdjqPqCET9X3rviPd27BkY40d+tH9mbkXifkPQhlbUVvU8MtZv3vpE9JbScb1EpQYO/pk/D72PXdu4mQnsG90vrK7xP6bJOePUTt4Gpt+s6q5RsEnd/805VPVKwFh14+wXr6m2fyKz5/bbuEVQg4we1+IUoCcYTAjcbeNaya9LYO+860U2V851wdJcUz8p95BQfzPtD+FcDcZ8hTiymPJUjw7bOdhSkYl8TQdcG0iKT0WFUxMDx9bTBjBILhigp+bZia9/1Mtj2Grw5nz9vt+WMr2wV69H7cj9f5w2VTTiXnRmap5C7KAHriW2RfExI6bEa6OPzN6l5Ld3XlRJfoZdmOn/zg3P/szKNU3Mnuzj4uLdlt5zyHkpExLYeQXGwp7hDzIyeRX1BzdhYgJ0smzty/I8GVEjk+CjWWZoFamFH1IBFNVrYGFxXfH0GBBRg7vNhqR+OEee2/xcSh3dh0hoZM=
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    tags: true
    rust: stable
    condition: $CLIPPY != true
