language: rust

git:
  depth: 1

addons:
  apt:
    packages:
      # For building MUSL static builds on Linux
      - musl-tools

matrix:
  fast_finish: true
  include:
    - rust: stable
      os: linux
      # Use MUSL so resulting binaries can be shared
      env: TARGET=x86_64-unknown-linux-musl
    - rust: nightly
      os: linux
      env: CLIPPY=true
    - rust: stable
      os: osx
    - rust: nightly
      os: osx
      env: CLIPPY=true
    - rust: stable
      os: windows
    - rust: nightly
      os: windows
      env: CLIPPY=true
  allow_failures:
    - rust: nightly
    - os: windows

install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install llvm --norestart --nosilent; fi
  - if [ -n "$CLIPPY" ]; then rustup component add clippy-preview; fi

script:
  - if [ -n "$CLIPPY" ]; then cargo clippy --all-features --all-targets; fi
  - if [ -z "$CLIPPY" ] && [ -n "$TRAVIS_TAG" ]; then cargo test --release; fi
  - if [ -z "$CLIPPY" ] && [ -z "$TRAVIS_TAG" ]; then cargo test; fi
  - if [ -z "$CLIPPY" ]; then cargo test -p font; fi

before_deploy:
  - ARCH=$(uname -m)
  - mkdir "./target/deploy"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      make dmg;
      mv "./target/release/osx/Alacritty.dmg" "./target/deploy/Alacritty-$TRAVIS_TAG.dmg";
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cargo install cargo-deb;
      DEB=$(cargo deb --no-build);
      mv "./target/release/alacritty" "./target/deploy/Alacritty-$TRAVIS_TAG-$ARCH";
      mv "$DEB" "./target/deploy/Alacritty-$TRAVIS_TAG-$ARCH.deb";
    fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      mv "./target/release/alacritty.exe" "./target/deploy/Alacritty-$TRAVIS_TAG-$ARCH.exe";
      mv "./target/release/winpty-agent.exe" "./target/deploy/winpty-agent.exe";
    fi

deploy:
  provider: releases
  api_key:
    secure: f/dzzrB8MmZsLl1BpeGw7Koz4+KmWlF8PCvLA7361TJHEZ+9WX95AB6IDsICzzwQR7+uyX14Qv+Xx7LQfUMrL8EBQDVU8cNFrEhhth+E8G+LwbJnG7DhlBXNz/GmPvz5r2fsuecVSyDhZr+t0Z2v1D/6qyEqruVTRGC76RgezzASb2ecJ0BQFfvwOWnX+J5mk9Ss8FQEohipu+EF9ItKP+QlTeWhl5qC9XNhiumYG/KHjujch8xX0TElY3AeRvqk2jyCoTFn17r4DI3/bh/4FuKMtNun5gh+qRkD79PT02qhZ1qFpaJqzO5HK0xQpUpnmHb1SGvizfHsCbioYXaSS1QmFIbEMUsBJ+Q/yKPGYWijjAmFfFtnd41J8631d1cgJrI+NyIehSgWCOliTHsdabiaFPO+o2zpKyr0eFX4VGiKdrf920dtMJMslhq4AEUG/nyv85SPbf3XMQ094O1jMJ9jOBnldfQL1u3udNQpgKwiKjLlQ/o4veWgBpujRdqKQzgaK7ntTKzplfgVx50OVxUhfIjDv9xhLIsKQEGVIcFlDMFBuNTI/B9WqwaMit3N9GX+yI+eBPs6hdKTLeUxs3sbBBNtVCKJPM1sz5B46KHE2wHQq+FTcyP7bO8D1Pvs/PhCJreE0WDHH2c++yeCzh368jkhbSpj2EOCSAho9VY=
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    tags: true
    rust: stable
