language: rust

sudo: required
services:
  - docker

git:
  depth: 1

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
    - os: windows

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: R2Au0H8Sp47d6gGgXrC+uEs+PWvf7JIwrzC6Gb3lt1Gly6Leya9W8HQ2nQIj7urqlIRNU7RLD7Qb26c8aMkMbDkyTavXaLKPMEGnTSlmbx5dkbzaDx7KrrSpUFkMq5L9mXNOgfkPVJWS7K5zcLHgSZxSJvi1H4QycujLHggOMCssEkquc0GSu+bPnfpkqpCwjGn+SfbRFL4oDg/ODvFc+X10FAc2CSkUSnPCustiip082lxT36z5hpV/4FcQzA1A2lEFzaOA1buP7IMO+SYhzph/2SOrJhpGO2a+AZwchwNiXoL7tAIQ3qYH1yqTUF84BM7l5gjl/nX0ftqlQke9MYC6fzwseDIPCxY8MeIFMpouuVWc1c3WXjsK+NCtD0V9HICL6N1wOsYPpZYwcSb1OIbpZ+W8q0SJ/Ec89KoYqBupDtKhi6pqAwxZ5yJ5RXsaRq7+rxFnoo2QtnEBMY+Q7LSDwzHNas2LFJQAitUTPjYJB/piVL7e42V2SBmS1LcCsb0/sXTTYArfCFYdEwOUwxr90KU8KSM5fViu/biYDq9zrURZgCkkhyH8B7B3zzf+uOY59+BMoYdXL9E/h+NXKlrRsS/6/jdTLJggjyu+hdh2SAON8NCAIQMbzQ7ZibgK/61Ib0HH0cDWVux4hB3PXqvProvY0lLySG2wUOh+b0s=
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    tags: true
    rust: stable
    repo: chrisduerr/alacritty
