language: rust
cache: cargo
service:
  - docker

notifications:
  webhooks:
    urls:
      - https://perf.christianduerr.com/notify
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always

os:
  - linux
  - osx

rust:
  - stable
  - nightly

env:
  - FEATURES="clippy"
  - FEATURES=""
  - DOCKER="true"

matrix:
  fast_finish: true
  exclude:
    - rust: stable
      env: FEATURES="clippy"
    - rust: nightly
      env: FEATURES=""
    - rust: nightly
      env: DOCKER="true"
    - rust: stable
      env: DOCKER="true"
      os: osx
  allow_failures:
    - rust: nightly

before_install:
  - if [[ -n "$DOCKER" ]]; then docker pull undeadleech/vtebench; fi
script:
  - if [[ -z "$DOCKER" ]]; then cargo test --no-default-features --features "$FEATURES"; fi
  - if [[ -n "$DOCKER" ]]; then bash ./headless-bench.sh; fi
