language: rust

addons:
  apt:
    packages:
    - libxcb-xfixes0-dev

git:
  depth: 1

os:
  - linux

rust:
  - stable

matrix:
  fast_finish: true
  include:
    - name: "Clippy Linux"
      os: linux
      env: CLIPPY=true
      rust: 1.43.1

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  - provider: releases
    api_key:
      secure: broken
    skip_cleanup: true
    file_glob: true
    file: "./target/deploy/*"
    on:
      tags: true
      rust: stable
      condition:
        - $CLIPPY == true
        - $CLIPPY != true
      repo: chrisduerr/alacritty
