language: rust

services:
  - docker

git:
  depth: 1

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  include:
    - if: tag IS present
      os: linux
      rust: stable
      env: ARCH=i386
  allow_failures:
    - rust: nightly
    - os: windows

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: RdV2KRi7OhJbWvv3trWzymeLX+Y43CaVeNIx3GURvRwEjpu/kW+PtBpFEr+snhMOwG7yGYaeY3GB9Qr5HR6+iAmEZ2lA68Aa+ioiyjDajJFb/Vi8EHbezm0tKWksYqaS87GLKijqthQ/RrcKsTP1zwDOGYgVhXjNTQiTlxCEO9YrUst+T5teiPXIXH960FS5ITjLXcOmcCgjFvukOXm86mc4pWS8g015cJJYZSY1l4c1dUmJM2fePV8dfeYW1YOlpMae/gMhroFZOLhlkNmeMaKi8fkmLO7VU2Yayw/aLNoTtLJp/9hDZ2cfp/icrv92/xH00lSqR2Pz+/gXCNmQkZqEA5HAkWk8lgy4XOyqf6iBehJWbQF30UdpiKFpPmFUkBWL/7WbrZ623tDPZOX1ZM65OrkWFfsGdQ7JfbYSdjv7RpcpOiZ34ZBh674JMRm6agDcUI3kjpYtye1JE+1PvLYntkdNRBsaMNXVj4mxs/BNP47gRtlvxVKRiGLO+AUqGugXj8gIWpLGN032rEQ9TgYlff41cfxlk6qElo3ngQnjMC9qDzs7lYk5OQNXs/2ywk3iv9s/PrG56tAeqQnZHtYfD6xy6mJJTnha51Bw7OQU7xtDYAuTWn0AgRzKf5wx/0DkIyyNJqppRZpJaPt73vs612SGwag2EeCVTHMcdro=
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    tags: true
    rust: stable
    repo: chrisduerr/alacritty
    branch: master
