language: rust

services:
  - docker

git:
  depth: 1

os:
  - linux
  - osx
  - windows

rust:
  - 1.32.0
  - stable
  - nightly

matrix:
  fast_finish: true
  include:
    - if: tag IS present
      os: linux
      rust: stable
      env: ARCH=i386
    - name: "Clippy Linux"
      os: linux
      env: CLIPPY=true
      rust: stable
    - name: "Clippy OSX"
      os: osx
      env: CLIPPY=true
      rust: stable
    - name: "Clippy Windows"
      os: windows
      env: CLIPPY=true
      rust: stable
    - name: "Rustfmt"
      os: linux
      env: RUSTFMT=true
      rust: nightly
  allow_failures:
    - rust: nightly

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: ZGKOg6U5M30Alu3rTDcJgHPhD0XcwMDAw1jCm2NBX0JRazZbwQx0LKzWW5UvSkjJEYsANgIumgNXSkfPZRvOH2nu50zsc2pUlx3AnrF9TGx9K+1S0TyMFvPCu4sqwBk460vuJ23NgIDpfP//fGdTaFZjblU7frDNiAie1rNCU/YI8r3tjNOqlmoNTPCLyIwuQkq3LXAe1jF8/In32XNGzqp4b5BDxmqeRIzQMBh0HCBq7zxkLfRkCmN1CJg8OAwYF0ZzuWh5E+fIZCjqjcAzLPm6c5UNmfBBIKJnVZCGE0cSFx++Zd2Y6Uu3RJuFN29WjTt5Dqr2mtACl3jp1ik7nfRwjflStGRyY5tQea4yT7AnVNNd4xq15LLMJMBHOkUhYd+eybc4jRk1GTYcpprBMOb9mEx6VlA1mFLeopYUvSDAvwK6BdqgOxPH+nT9dmO+VTAU3xgn7xRL2A1vidMl3rNkGU73FjY/7CXtDcDLRODphlirC0CjVGHkYAjHvWA44Qlx0dEqkli22XoOyBmM6kFprw76yYxtohBuuKH5zb3qRtEMJrap/TicKs0xUSfHGLaO7Ic/fGGAdJ8ZwCwsjfzc2pVi0yGliAOoi7ejTl1z3ZqPzpgjMczbfK/ZRFGMPyzsPORsRW6+lID8yuRAjkXd4GRtyR1UAfYQ9ahbUcE=
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    tags: true
    rust: stable
    condition: $CLIPPY != true
