language: rust
sudo: false

cache: cargo

notifications:
  webhooks:
    urls:
      - https://perf.christianduerr.com/notify
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
    on_cancel: never # default: always
    on_error: never # default: always

os:
  - linux
  - osx

rust:
  - stable
  - nightly

env:
  - FEATURES="clippy"
  - FEATURES=""

matrix:
  fast_finish: true
  exclude:
    - rust: stable
      env: FEATURES="clippy"
    - rust: nightly
      env: FEATURES=""
  allow_failures:
    - rust: nightly

script:
  - cargo test --no-default-features --features "$FEATURES"
