[workspace]
members = [
    "alacritty",
    "alacritty_font",
    "alacritty_terminal",
    "copypasta",
    "winpty"
]

[profile.release]
lto = true
debug = 1
incremental = false

[patch.crates-io]
servo-freetype-sys = { path = "servo-freetype-proxy" }
